[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pycloak"
version = "0.1.0"
dependencies = [
    "click",
]

[project.scripts]
pycloak = "pycloak.cli:main"